#pragma once

// GreeterModule.internal.h is generated by ReBuildTool and defines GREETERMODULE_API as
// dllexport while this module is being compiled, and dllimport for any consumer.
#include "GreeterModule.internal.h"

class GREETERMODULE_API Greeter
{
public:
    int Add(int a, int b);
    const char* Greeting();
};
