using System.Text;
using NiceIO;

using ResetCore.Common;

namespace ReBuildTool.ToolChain;

/// <summary>
/// Serializes build edges into the <c>build.ninja</c> file format. Plays the same
/// role for the Ninja backend as <see cref="MakeFileGenerator"/> does for the
/// Makefile backend, but emits Ninja's <c>rule</c>/<c>build</c> syntax instead of
/// make's <c>target: deps</c> + tab-recipes.
/// <para>
/// Design notes for Phase-2-readiness: rules use <c>command = $cc $args</c> with the
/// per-edge <c>$cc</c>/<c>$args</c> variables, so a later phase can add
/// <c>depfile = $out.d</c> + <c>deps = gcc</c>/<c>msvc</c> without restructuring the
/// generator.
/// </para>
/// </summary>
public class NinjaFileGenerator
{
    public const string CxxRuleName = "cxx";
    public const string LinkRuleName = "link";
    public const string ArchiveRuleName = "ar";

    /// <summary>
    /// A Ninja <c>rule</c> block. All three rules share the same
    /// <c>command = $cc $args</c> shape; the per-edge <c>cc</c>/<c>args</c>
    /// variables carry the actual tool + flags.
    /// </summary>
    public class Rule
    {
        public Rule(string name)
        {
            Name = name;
        }

        public string Name { get; }

        /// <summary>
        /// Optional dependency-trait annotation (<c>deps = gcc</c> / <c>deps = msvc</c>).
        /// Null in Phase 1; Phase 2 populates this together with <see cref="Depfile"/>.
        /// </summary>
        public string? Deps { get; set; }

        /// <summary>
        /// Optional <c>depfile</c> template, e.g. <c>$out.d</c>. Null in Phase 1.
        /// </summary>
        public string? Depfile { get; set; }
    }

    /// <summary>
    /// A Ninja <c>build</c> edge: <c>build $out: $rule $in | $implicit_deps</c>
    /// followed by indented variable assignments.
    /// <para>
    /// Paths are held as <see cref="NPath"/> and escaped by the generator when the edge is
    /// written (see <see cref="NinjaPath"/>), so a caller cannot forget to escape — or
    /// escape twice. Variable values are shell command-line fragments the caller has
    /// already quoted with <c>ShellQuote</c>; the generator adds the ninja-level escape on
    /// top of them (see <see cref="NinjaValue"/>).
    /// </para>
    /// </summary>
    public class Edge
    {
        public Edge(NPath output, string ruleName)
        {
            Output = output;
            RuleName = ruleName;
        }

        public NPath Output { get; }
        public string RuleName { get; }
        public List<NPath> ExplicitInputs { get; } = new();
        /// <summary>Implicit dependencies (<c>| ...</c>): they trigger a rebuild of $out like
        /// explicit inputs do, but are not substituted into <c>$in</c>.</summary>
        public List<NPath> ImplicitInputs { get; } = new();
        /// <summary>Per-edge variable bindings emitted as <c>key = value</c> lines under the edge.</summary>
        public List<KeyValuePair<string, string>> Variables { get; } = new();

        public Edge WithInput(NPath input)
        {
            ExplicitInputs.Add(input);
            return this;
        }

        public Edge WithImplicitInput(NPath input)
        {
            ImplicitInputs.Add(input);
            return this;
        }

        public Edge WithVariable(string key, string value)
        {
            Variables.Add(new KeyValuePair<string, string>(key, value));
            return this;
        }
    }

    public List<Rule> Rules { get; } = new();
    public List<Edge> Edges { get; } = new();

    /// <summary>
    /// When non-null, emitted as a top-level <c>msvc_deps_prefix = ...</c> line. Required
    /// by ninja whenever any rule uses <c>deps = msvc</c>: ninja scans cl.exe's stdout
    /// for lines beginning with this prefix (under <c>VSLANG=1033</c> that's
    /// "Note: including file:") to discover header dependencies. Set by the Ninja build
    /// backend when the active toolchain is MSVC-family; left null otherwise.
    /// </summary>
    public string? MsvcDepsPrefix { get; set; }

    /// <summary>Registers the three canonical rules once each.</summary>
    public Rule EnsureRule(string name)
    {
        var existing = Rules.FirstOrDefault(r => r.Name == name);
        if (existing != null)
        {
            return existing;
        }
        var rule = new Rule(name);
        Rules.Add(rule);
        return rule;
    }

    public void FlushToFile(NPath output)
    {
        // Build the file with a plain StringBuilder rather than SourceCodeBuilder:
        // ninja is whitespace-sensitive — rule/build block variables must be indented
        // with SPACES, but SourceCodeBuilder.AddIndent emits tabs (the Make convention),
        // which ninja rejects with "expected 'command =' line".
        var sb = new StringBuilder();

        // Header comment — helps debugging the generated file.
        sb.AppendLine("# Auto-generated by ReBuildTool (Ninja backend). Do not edit.");
        sb.AppendLine("# Each rule delegates its command to per-edge $cc/$args variables so");
        sb.AppendLine("# Phase 2 can attach depfile/deps without restructuring.");
        sb.AppendLine();

        // Top-level msvc_deps_prefix — must appear before any rule using deps = msvc.
        // Emitted only when the active toolchain is MSVC-family (cl.exe / clang-cl).
        if (!string.IsNullOrEmpty(MsvcDepsPrefix))
        {
            sb.AppendLine($"msvc_deps_prefix = {MsvcDepsPrefix}");
            sb.AppendLine();
        }

        foreach (var rule in Rules)
        {
            FlushRule(sb, rule);
            sb.AppendLine();
        }

        foreach (var edge in Edges)
        {
            FlushEdge(sb, edge);
        }

        var content = sb.ToString();

        // Idempotency: skip the write if the on-disk file already has identical
        // content. Matches MakeFileGenerator.FlushToFile behaviour and avoids
        // bumping ninja's mtime (which would force a re-stat on next run).
        if (output.Exists() && output.ReadAllText() == content)
        {
            Log.Info("build.ninja is not changed, skip writing");
            return;
        }

        output.WriteAllText(content);
    }

    private static void FlushRule(StringBuilder sb, Rule rule)
    {
        sb.AppendLine($"rule {rule.Name}");
        // 2-space indent — ninja requires spaces here, not tabs.
        sb.AppendLine($"  command = $cc $args");
        if (!string.IsNullOrEmpty(rule.Depfile))
        {
            sb.AppendLine($"  depfile = {rule.Depfile}");
        }
        if (!string.IsNullOrEmpty(rule.Deps))
        {
            sb.AppendLine($"  deps = {rule.Deps}");
        }
    }

    private static void FlushEdge(StringBuilder sb, Edge edge)
    {
        // build <out>: <rule> <inputs> | <implicit inputs>
        // The generator owns the ninja-level escaping: paths go through NinjaPath here (the
        // Edge holds them raw), so no call site can forget it or apply it twice.
        sb.Append($"build {NinjaPath(edge.Output)}: {edge.RuleName}");
        foreach (var input in edge.ExplicitInputs)
        {
            sb.Append($" {NinjaPath(input)}");
        }
        if (edge.ImplicitInputs.Count > 0)
        {
            sb.Append(" |");
            foreach (var implicitInput in edge.ImplicitInputs)
            {
                sb.Append($" {NinjaPath(implicitInput)}");
            }
        }
        sb.AppendLine();

        // Per-edge variables: 2-space indent (`key = value`). The value arrives shell-quoted
        // from the caller (ninja runs `command = $cc $args` through a shell); NinjaValue adds
        // the ninja-level escape on top so a literal '$' survives ninja's own lexer.
        foreach (var kvp in edge.Variables)
        {
            sb.AppendLine($"  {kvp.Key} = {NinjaValue(kvp.Value)}");
        }
        sb.AppendLine();
    }

    /// <summary>
    /// Escapes an <see cref="NPath"/> for use as a build-edge input/output or
    /// explicit/implicit dependency (the structural positions on a <c>build</c>
    /// line). Four transformations:
    /// <list type="bullet">
    /// <item>Backslashes → forward slashes: ninja is a POSIX-ish lexer and treats
    /// <c>\</c> as an escape; forward slashes work on all platforms and MSVC's
    /// cl/link accept them too.</item>
    /// <item><c>:</c> → <c>$:</c>: a bare colon in a build-line position is what
    /// separates <c>build OUTPUTS: RULE</c>, so a Windows drive letter like
    /// <c>D:</c> makes ninja error with "expected build command name". Escaping
    /// the colon with <c>$:</c> tells ninja's lexer to treat it literally while
    /// still producing <c>D:</c> in the actual path. (Only needed in structural
    /// positions — inside <c>args = ...</c> variable values, colons are literal.)</item>
    /// <item>Space → <c>$ </c> (dollar+space) PER space: ninja's path-list escape for a
    /// literal space is <c>$ </c>, applied to each space individually — NOT a
    /// <c>$ ... $</c> wrapper around the whole path. e.g. <c>C:/My Dir/x.o</c> becomes
    /// <c>C$:/My$ Dir/x.o</c>. (Wrapping broke ninja's build-line parser — it treats the
    /// wrapped token as a different statement and errors "expected build command name".)</item>
    /// <item><c>$</c> → <c>$$</c>: <c>$</c> is ninja's own escape character, so a literal one
    /// in a path has to be doubled or ninja rejects the file with "bad $-escape".</item>
    /// </list>
    /// </summary>
    public static string NinjaPath(NPath path)
    {
        return NinjaPathToken(path.ToString());
    }

    /// <summary>
    /// <see cref="NinjaPath"/> on a raw path string. Split out so the escaping can be exercised
    /// directly with paths that do not exist (and that <see cref="NPath"/> would normalise) on
    /// whichever host the tests run on.
    /// </summary>
    public static string NinjaPathToken(string path)
    {
        var str = path.Replace('\\', '/');
        // Order matters: double the path's own '$' FIRST, so the '$' characters the next two
        // steps introduce (as the escapes '$:' and '$ ') are not doubled in turn.
        str = str.Replace("$", "$$");
        str = str.Replace(":", "$:");
        // Escape each space as "$ " (ninja's literal-space escape for path-list positions).
        str = str.Replace(" ", "$ ");
        return str;
    }

    /// <summary>
    /// Escapes a shell command-line fragment for use as a ninja <em>variable value</em> (the
    /// right-hand side of <c>cc = ...</c> / <c>args = ...</c>). Only <c>$</c> is significant
    /// there — it must be doubled, or ninja fails the file with "bad $-escape (literal $ must
    /// be written as $$)". Colons and spaces are literal in this position, so unlike
    /// <see cref="NinjaPath"/> they are left alone: the shell-level quoting the caller
    /// applied is what keeps the value one argv token at execution time.
    /// </summary>
    public static string NinjaValue(string value)
    {
        return value.Replace("$", "$$");
    }
}
