using NiceIO;
using ReBuildTool.Service.PackageService;
using ResetCore.Common;

namespace ReBuildTool.ToolChain.Package;

/// <summary>
/// Turns restored packages into things the rule glob can pick up.
///
/// Source packages need nothing - they already carry <c>.module.cs</c> files. The two shapes that
/// do need work are handled here:
///
///  - a <b>prebuilt binary package</b> has headers and libraries but no rule, so a module rule is
///    generated for it;
///  - an <b>unmodified upstream source tree</b> has neither, so the consuming project supplies a
///    rule through the dependency's <c>overlay</c> field and it is copied into place.
///
/// Generating a rule file, rather than registering an IModuleInterface directly into ModuleRules,
/// keeps everything downstream working for free: the ModuleRulePaths lookup in InitAllRule (which
/// throws for a module it has no path for), the SetupInternal lifecycle, the _API macro codegen,
/// all four IDE generators and the HeaderTool plugin.
/// </summary>
public static class PackageModuleBinder
{
	/// <summary>Generated rules live here, one directory per module, under Packages/.</summary>
	public const string GeneratedFolderName = ".generated";

	/// <summary>
	/// Writes whatever rule files the restored packages imply and returns the extra directories
	/// <c>ParseRules</c> should glob in addition to the packages themselves.
	/// </summary>
	public static List<NPath> Bind(NPath packagesRoot, IEnumerable<RestoredPackage> packages)
	{
		var roots = new List<NPath>();
		// Two binary packages are free to pick the same binary.module name, and both would generate
		// to Packages/.generated/<module>/<module>.module.cs - the same file. The second write would
		// simply win, leaving the build silently dependent on which package happened to come last.
		// (A collision between two *source* packages is caught later, in ParseRules, because those
		// are two distinct files claiming one module name. This path has to catch its own.)
		var generatedBy = new Dictionary<string, string>();
		foreach (var package in packages)
		{
			var generated = BindOne(packagesRoot, package, generatedBy);
			if (generated != null)
			{
				roots.Add(generated);
			}
		}
		return roots;
	}

	private static NPath? BindOne(
		NPath packagesRoot,
		RestoredPackage package,
		Dictionary<string, string> generatedBy)
	{
		InstallOverlay(package);

		var binary = package.Manifest?.Binary;
		if (binary == null)
		{
			return null;
		}

		// The name comes out of the package's own manifest, which for a remote package is not the
		// consuming project's to trust. It is interpolated into a directory name and into the
		// "public class <name>" of a generated rule that rbt then compiles and runs, so anything
		// other than a plain identifier is rejected rather than escaped.
		var moduleName = PackageNames.ValidateModuleName(
			string.IsNullOrWhiteSpace(binary.Module) ? package.Name : binary.Module!,
			package.Name);

		if (generatedBy.TryGetValue(moduleName, out var owner))
		{
			throw new Exception(
				$"packages \"{owner}\" and \"{package.Name}\" both provide a module named " +
				$"\"{moduleName}\". Only one of them can, since a module is depended on by name - " +
				$"set a distinct \"module\" in one package's {PackageManifest.FileName}.");
		}
		generatedBy.Add(moduleName, package.Name);
		var moduleDirectory = packagesRoot.Combine(GeneratedFolderName, moduleName);
		// The framework unconditionally registers a module's Public/ and Private/ directories; the
		// source globbing warns once per missing path, so create them rather than emit noise.
		moduleDirectory.Combine("Public").EnsureDirectoryExists();
		moduleDirectory.Combine("Private").EnsureDirectoryExists();

		var manifestPath = PackageManifest.PathIn(package.Root).ToString().Replace("\\", "\\\\");
		var content =
			$"// Generated by rbt for the binary package \"{package.Name}\". Do not edit - it is{Environment.NewLine}" +
			$"// rewritten from {PackageManifest.FileName} on every restore.{Environment.NewLine}" +
			$"using ReBuildTool.Service.CompileService;{Environment.NewLine}" +
			$"using ReBuildTool.ToolChain;{Environment.NewLine}" +
			$"using ReBuildTool.ToolChain.Package;{Environment.NewLine}" +
			$"{Environment.NewLine}" +
			$"public class {moduleName} : CppModuleRule{Environment.NewLine}" +
			$"{{{Environment.NewLine}" +
			$"    public override void Setup(ICppBuildContext buildContext){Environment.NewLine}" +
			$"    {{{Environment.NewLine}" +
			$"        TargetBuildType = BuildType.StaticLibrary;{Environment.NewLine}" +
			// The artifact table is read at Setup time so this file stays platform-independent.
			$"        PackageArtifactSelector.Apply(this, buildContext, \"{manifestPath}\");{Environment.NewLine}" +
			$"    }}{Environment.NewLine}" +
			$"}}{Environment.NewLine}";

		WriteIfChanged(moduleDirectory.Combine($"{moduleName}.module.cs"), content);
		Log.Info($"[package] {package.Name} provides prebuilt module {moduleName}");
		return moduleDirectory;
	}

	/// <summary>
	/// Copies a consumer-supplied rule file into the package it describes.
	///
	/// It has to land in the package root, not in a generated directory alongside it: the rule's
	/// <c>ModuleDirectory</c> becomes wherever the file sits, and every relative path an overlay
	/// declares - <c>SourceDirectories</c>, <c>SourceFiles</c>, <c>ExcludeDirectories</c> - is
	/// resolved against it. Those paths only make sense relative to the upstream tree.
	/// </summary>
	private static void InstallOverlay(RestoredPackage package)
	{
		if (package.Overlay == null)
		{
			return;
		}

		var destination = package.Root.Combine(package.Overlay.FileName);
		WriteIfChanged(destination, package.Overlay.ReadAllText());
		Log.Info($"[package] {package.Name} uses overlay rule {package.Overlay.FileName}");
	}

	/// <summary>
	/// Only writes when the content differs. Rewriting unconditionally would bump the file's
	/// timestamp on every restore, and NeedReBuildRuleAssembly compares timestamps - the whole rule
	/// assembly would be recompiled on each build. Same reasoning as CppModuleRule.GenerateCode.
	/// </summary>
	internal static void WriteIfChanged(NPath path, string content)
	{
		if (path.FileExists() && path.ReadAllText() == content)
		{
			return;
		}
		path.EnsureParentDirectoryExists();
		path.WriteAllText(content);
	}
}
